<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Messages\DeleteMessage\" />
    <Folder Include="Messages\AddMessage\" />
    <Folder Include="Messages\GetMessageById\" />
    <Folder Include="Messages\Get10RepliesByPost\" />
    <Folder Include="Messages\Get10PostByUser\" />
    <Folder Include="Messages\Get10RepliesByUser\" />
    <Folder Include="Pagination\" />
    <Folder Include="Photos\GetPhotoById\" />
    <Folder Include="Photos\Get10PhotosByUser\" />
    <Folder Include="Photos\DeletePhoto\" />
    <Folder Include="Photos\UploadPhoto\" />
    <Folder Include="Reactions\EditReactionToMessage\" />
    <Folder Include="Reactions\GetReactionsByUser\" />
    <Folder Include="Reactions\GetReactionsByMessage\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SocialMedia.Domain\SocialMedia.Domain.csproj" />
  </ItemGroup>

</Project>
